### ISSUE TITLE
请问如何收藏？

### ISSUE THREAD

**Issue by laozhu999** [zbefine/iptv#1]
首先感谢你的付出，不敢有太多奢望，觉得做的非常棒。问一下怎么才能看到所有频道呢？尤其是外语类的😅

**Comment by zbefine** [comment]
在视频控制条里，如果有 ☆ 五角星图标， 点击即可收藏！有部分频道是不支持收藏的。

所有频道的视频地址每天都会检测有效性，地址有效小程序才会收录，外语类的频道因为墙的原因，哪怕翻墙播放视频还是卡、很不稳定，所以没收录。不便之处，敬请谅解。

**Comment by laozhu999** [comment]
谢谢，还有比赛看，真是太棒啦，外语新闻就自己去搞了，谢谢啦
