### ISSUE TITLE
请问怎么样在浏览器中打开m3u文件，而不是下载？

### ISSUE THREAD

**Issue by RookieTerry** [zbefine/iptv#9]
如题，我想在浏览器中查看m3u文件的内容，而不是下载它，请问我应该怎么设置http请求头？

**Comment by oyps** [comment]
将响应头中的 `Content-Type` 设置为 `text/plain` 即可，或者使用 Ajax 进行请求拿到响应的文本内容，也可使用在线模拟请求工具查看，如：http://i.apee.top/mnqq/，希望有用

**Comment by RookieTerry** [comment]
> 

谢谢大佬，这样确实是查看而不是下载了。但是这样设置以后浏览器查看到的是乱码，请问请求头还需要再添加什么吗？

**Comment by RookieTerry** [comment]
> > 将响应头中的 `Content-Type` 设置为 `text/plain` 即可，或者使用 Ajax 进行请求拿到响应的文本内容，也可使用在线模拟请求工具查看，如：[http://i.apee.top/mnqq/，希望有用](http://i.apee.top/mnqq/%EF%BC%8C%E5%B8%8C%E6%9C%9B%E6%9C%89%E7%94%A8)
> 
> 谢谢大佬，这样确实是查看而不是下载了。但是这样设置以后浏览器查看到的是乱码，请问响应头还需要再添加什么吗？

解决了，把响应头中的`Content-Type`设置为`text/plain;charset=utf-8`即可。话说为什么这里的`Content-Type`是在响应头中，而不是请求头中呢？

**Comment by oyps** [comment]
> 

响应头中的 `Content-Type` 可以告诉浏览器，需要使用何种编码规则来解析数据。如果设置错误，比如服务器上有一个 UTF-8 的文本文件，但浏览器拿到的响应头中的 `Content-Type` 却是 GBK，浏览器就用 GBK 的规则去解析响应的内容，就出现了乱码。如果乱码了，可以使用相关的浏览器插件，手动指定浏览器以何种编码规则去解析数据，而不是直接使用响应头 `Content-Type` 中的编码

**Comment by oyps** [comment]
响应头中的 Content-Type 可以告诉浏览器，需要使用何种编码规则来解析数据。如果设置错误，比如服务器上有一个 UTF-8 的文本文件，但浏览器拿到的响应头中的 Content-Type 却是 GBK，浏览器就用 GBK 的规则去解析响应的内容，就出现了乱码。如果乱码了，可以使用相关的浏览器插件，手动指定浏览器以何种编码规则去解析数据，而不是直接使用响应头 Content-Type 中的编码

**Comment by RookieTerry** [comment]
> 响应头中的 `Content-Type` 可以告诉浏览器，需要使用何种编码规则来解析数据。如果设置错误，比如服务器上有一个 UTF-8 的文本文件，但浏览器拿到的响应头中的 `Content-Type` 却是 GBK，浏览器就用 GBK 的规则去解析响应的内容，就出现了乱码。如果乱码了，可以使用相关的浏览器插件，手动指定浏览器以何种编码规则去解析数据，而不是直接使用响应头 `Content-Type` 中的编码

好的，谢谢大佬解答！
